### ISSUE TITLE
Err 503 on adding datapoint to a Flow requiring a signed payload

### ISSUE THREAD

**Issue by mathcoll** [mathcoll/t6#19]
**Describe the bug**
Err 503 on adding datapoint to a Flow requiring a signed payload

**To Reproduce**
1. create a Flow with attribute: `"require_signed": true` and an object having its own `secret_key`
2. POST /data to that Flow without any signed payload
3. Server is currently responding a 503

`
      at signatureCheck (/media/Documents/Projets/2019/internetcollaboratif.info/t6/routes/data.js:98:7)
      at nextTask (/media/Documents/Projets/2019/internetcollaboratif.info/t6/node_modules/async/dist/async.js:5756:27)
      at next (/media/Documents/Projets/2019/internetcollaboratif.info/t6/node_modules/async/dist/async.js:5764:13)
]
Trace: Error: Error: Callback was already called.
    at process.<anonymous> (/media/Documents/Projets/2019/internetcollaboratif.info/t6/node_modules/libnmap/lib/libnmap.js:116:17)
    at process.emit (node:events:388:22)
    at process._fatalException (node:internal/process/execution:163:25)
    at processPromiseRejections (node:internal/process/promises:227:11)
    at processTicksAndRejections (node:internal/process/task_queues:94:32)
    at process.<anonymous> (/media/Documents/Projets/2019/internetcollaboratif.info/t6/node_modules/libnmap/lib/libnmap.js:116:11)
    at process.emit (node:events:388:22)
    at process._fatalException (node:internal/process/execution:163:25)
    at processPromiseRejections (node:internal/process/promises:227:11)
    at processTicksAndRejections (node:internal/process/task_queues:94:32)
02/Oct/2021:21:02:56 +0200 [0m[31m[ERROR] [
`

**Expected behavior**
201 status code and success response

**Comment by mathcoll** [comment]
Fixed 8010061657d7e2508452227f1e3d4415b0cb43d0

**Comment by mathcoll** [comment]
Fixed 71a4b4b6cbd84786427cfbf75c1ff21186364131 and 59e8494db595abc22c404b984e4d952092f525f0
